calibrated: 1
equilibrium:
    sign: -1
    signFlexor: -1
    signExtensor: -1
    nameFlexor: "shoulder_adductor"
    nameExtensor: "shoulder_abductor"
    servoRange: 6.2832
    servoOffset: 0.3
    loadLimit: 0.5  # Testing limitLoad method in equilibrium_model.py.
signEncoder: -1
signJoint: 1
name: "shoulder_pitch"
nameEncoder: "shoulder_pitch_encoder"
minAngle: -0.15
maxAngle: 1.45
maxAbsForwardError: 0.25
gains:
    P: 0.055
    I: 0.00002
    D: 0.025
restingPoseAngle: 0.0 # Parameter to adjusting resting pose joint angle.
